Repository engineyard/ey-cookbooks-stable-v5, pull requests merged in 2018-08, with the labels that each got.

#325 [YT-CC-1217] credits section, support license key from NR add-on and display name
  cookbooks/newrelic_infra/attributes/default.rb
  cookbooks/newrelic_infra/metadata.rb
  cookbooks/newrelic_infra/recipes/default.rb
  cookbooks/newrelic_infra/templates/default/newrelic-infra.yml.erb
  custom-cookbooks/newrelic_infra/cookbooks/custom-newrelic_infra/README.md
  custom-cookbooks/newrelic_infra/cookbooks/custom-newrelic_infra/attributes/default.rb
Labels: LGTM

#323 [YT-CC-1204] Adds orphan monitoring to the sidekiq recipe
  cookbooks/sidekiq/attributes/default.rb
  cookbooks/sidekiq/files/default/sidekiq_orphan_monitor
  cookbooks/sidekiq/recipes/setup.rb
Labels: LGTM

#321 [CC-1179] Hide passenger version on X-Powered-By header
  cookbooks/nginx/templates/default/server.conf.erb
  cookbooks/nginx/templates/default/ssl.conf.erb
  cookbooks/passenger5/templates/default/nginx_app.conf.erb
Labels: LGTM

#318 [CC-1089] HTTPS param not set for FastCGI applications
  cookbooks/nginx/templates/default/common.fcgi.conf.erb
  cookbooks/nginx/templates/default/nginx-plusplus.conf.erb
Labels: LGTM

#132 [Custom] Update custom db-libs
  cookbooks/db_client_libs/README.md
  cookbooks/db_client_libs/metadata.rb
  cookbooks/db_client_libs/recipes/default.rb
Labels: LGTM, custom

#322 db-ssl timeouts and corrections
  cookbooks/db-ssl/templates/default/remote_key_copy.sh.erb
Labels: LGTM, bug, enhancement

#357 [CC-1248] Support for Ruby 2.5
  cookbooks/ey-lib/libraries/ey-environment.rb
  cookbooks/ruby/recipes/ruby.rb
Labels: LGTM
